version: "3.9"
services:
  fastapi-template:
    build: .
    container_name: fastapi-template
    ports:
      - "443:443"
    env_file: .docker.env
    networks:
      - postgres_network
      - redis_network
      - kafka_network
      - elastic_network
      - jaeger_network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.25"
        reservations:
          memory: 512M
          cpus: "0.25"

networks:
  postgres_network:
    name: postgres_network
    external: true
  redis_network:
    name: redis_network
    external: true
  kafka_network:
    name: kafka_network
    external: true
  elastic_network:
    name: elastic_network
    external: true
  jaeger_network:
    name: jaeger_network
    external: true
