version: '3.9'
services:
  fastapi-template:
    build: .
    container_name: fastapi-template
    ports:
      - '443:443'
    environment:
      - ENVIRONMENT=
      - DATABASE_NAME=
      - DATABASE_HOST=
      - DATABASE_PORT=
      - DATABASE_USER=
      - DATABASE_PASSWORD=
      - KAFKA_CLIENT_ID=
      - KAFKA_GROUP_ID=
      - KAFKA_BROKERS=
      - ELASTICSEARCH_HOSTS=
      - SECURITY_JWKS_URL=
      - SECURITY_AUDIENCE=
      - CACHE_REDIS_HOST=
      - AWS_PROFILE=
      - AWS_DEFAULT_REGION=
    networks:
      - postgres_network
      - redis_network
      - kafka_network
      - elastic_network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
    mem_limit: 536870912
    cpus: 0.25

networks:
  postgres_network:
    name: postgres_network
    external: true
  redis_network:
    name: redis_network
    external: true
  kafka_network:
    name: kafka_network
    external: true
  elastic_network:
    name: elastic_network
    external: true
