apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
  namespace: template
type: Opaque
data:
  DATABASE_PRIMARY_PASSWORD:
  DATABASE_READONLY_PASSWORD:
  SECURITY_ENCRYPTION_PASSWORD:
  SECURITY_ENCRYPTION_SALT:
